### ISSUE TITLE
ReferenceError: atob is not defined

### ISSUE THREAD

**Issue by aBuder** [FUUbi/digital-covid-certificate-lib#4]
Hi,

we got this error when we try to validate the covid certificate

```log
 functions: ReferenceError: atob is not defined
    at new Jwt (/Users/abuder/projects/softwarenetz/butterfly-firebase/functions/node_modules/digital-covid-certificate-lib/dist/crypto/Jwt.js:12:28)
    at /Users/abuder/projects/softwarenetz/butterfly-firebase/functions/lib/index.js:163:14
    at /usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:604:16
    at runFunction (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:583:15)
    at runHTTPS (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:603:11)
    at handler (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:532:23)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/firebase-tools/node_modules/express/lib/router/layer.js:95:5)
⚠  Your function was killed because it raised an unhandled error.
```

**Comment by fuubi** [comment]
The runtime environment that you are using does not implement the Web Api function atob which is used to decode a base64 string. Please have a look at the [Mozilla Doc](https://developer.mozilla.org/en-US/docs/Web/API/atob) and provide the function with the described polyfill.

**Comment by fuubi** [comment]
@aBuder, I will close the Issue as it was a platform-related problem. Feel free to file a pull request with an example of integrating it within the platform you are using.
